apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
  # - name: https
  #   port: 443
  #   protocol: TCP
  #   targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: api-gateway
