POST http://localhost:8080/api/v1/epreuves
Content-Type: application/json

{
	"nom": "math",
	"analyseId": 3
}

###

GET http://localhost:8080/api/v1/epreuves

###

GET http://localhost:8080/api/v1/epreuves/2

###

DELETE http://localhost:8080/api/v1/epreuves/2
