services:
  gestionanalyse:
    build: .
    image: amidrissi/gestion_analyse:dev-0.0.1
    networks:
      - app-demo
    stdin_open: true
    tty: true
    ports:
      - "9998:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://psqldb:5432/ami
      POSTGRES_DB_USERNAME: ami
      POSTGRES_DB_PASSWORD: pwd

networks:
  app-demo:
    name: app-demo-net
    driver: bridge
    external: true