apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-analyse-deployment
  labels:
    app: gestion-analyse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-analyse
  template:
    metadata:
      labels:
        app: gestion-analyse
    spec:
      containers:
        - name: gestion-analyse
          image: registry.gitlab.com/webs2435142/new-proj/gestion-analyse:0.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: analyse-db-secrets
      imagePullSecrets:
        - name: regcred

