apiVersion: v1
kind: Service
metadata:
  name: gestion-utilisateur-service
  labels:
    app: gestion-utilisateur
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gestion-utilisateur
