spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contact_management
    username: ismail
    password: ismail
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      file: ./gestion-contact/compose.yaml
