apiVersion: v1
kind: Service
metadata:
  name: gestion-exam-service
  labels:
    app: gestion-exam
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gestion-exam
  sessionAffinity: None
