apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-laboratoire-deployment
  labels:
    app: gestion-laboratoire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-laboratoire
  template:
    metadata:
      labels:
        app: gestion-laboratoire
    spec:
      containers:
        - name: gestion-laboratoire
          image: registry.gitlab.com/webs2435142/new-proj/gestion-laboratoire:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: db-secrets
      imagePullSecrets:
        - name: regcred

