apiVersion: v1
kind: Service
metadata:
  name: gestion-laboratoire-service
  labels:
    app: gestion-laboratoire
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gestion-laboratoire
