# Generated by Django 5.1 on 2024-10-14 13:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nrc', models.IntegerField()),
                ('logo', models.ImageField(upload_to='labo/logos')),
                ('active', models.BooleanField(default=True)),
                ('date_activation', models.DateField(default=datetime.date(2024, 10, 14))),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('idFkLaboratoire', models.ForeignKey(db_column='idFkLaboratoire', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='my_api.laboratoire')),
            ],
        ),
    ]
