# Generated by Django 5.1 on 2024-10-23 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='analyse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
