apiVersion: v1
kind: Service
metadata:
  name: gestion-integration-service
  labels:
    app: gestion-integration
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gestion-integration
