name: Api Gateway

on:
  push:
    branches: [ "master" ]
    paths:
      - 'api_gateway/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'api_gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # Should clone frontend and build the frontend files and then store them.
      # We'll figure out updating the frontend without caddy later
    - name: Clone frontend github repo

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd api_gateway
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      run: |
          cd api_gateway/test
          python test.py
