name: Gestion Exam CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'gestion-exam/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'gestion-exam/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Build
      run: |
        cd gestion-exam
        cargo build --verbose
    
    - name: Run tests
      run: |
        cd gestion-exam
        cargo test --verbose

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deploy to production
      run: |
        # Add deployment steps here
        echo "Deploying gestion-exam to production"
