name: Gestion Contact CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'gestion-contact/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'gestion-contact/**'

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Compile project
        run: |
          cd gestion-contact
          chmod +x ./gradlew
          ./gradlew compileJava
          ./gradlew compileTestJava

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Running Unit Tests
        run: |
          cd gestion-contact
          chmod +x ./gradlew
          ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: gestion-contact/build/reports/tests/

  sonar-qube:
    runs-on: self-hosted
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
          cd gestion-contact
          ./gradlew sonar \
            -Dsonar.projectKey=gestion-contact \
            -Dsonar.projectName='gestion-contact' \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        shell: powershell

  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [sonar-qube]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build project
        run: |
          cd gestion-contact
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: gestion-contact/build/libs/*.jar

  integration-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Integration Tests
        run: |
          # Add Integration test steps here
          echo "Integration tests for gestion-contact"

  performance-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Performance Tests
        run: |
          # Add Performance test steps here
          echo "Performance tests for gestion-contact"

  containerize:
    runs-on: ubuntu-latest
    needs: performance-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: gestion-contact/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./gestion-contact
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gestion-contact:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/gestion-contact:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gestion-contact:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gestion-contact:buildcache,mode=max

  deploy:
    needs: containerize
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to production
        run: |
          # Add deployment steps here
          echo "Deploying gestion-contact to production"

  e2e-tests:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: E2E Tests
        run: |
          # Add E2E test steps here
          echo "E2E tests for gestion-contact"
