name: Gestion Exam Resultat CI/CD

on:
  push:
    branches: [ "master" ]
    paths:
      - 'gestion-exam-resultat/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'gestion-exam-resultat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Build
      run: |
        cd gestion-exam-resultat
        cargo build --release --verbose
    
    - name: Run tests
      run: |
        cd gestion-exam-resultat
        cargo test --verbose

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Build and push docker image
      env:
        CONTAINER_REGISTRY: ${{secrets.CONTAINER_REGISTRY}}
        CONTAINER_REGISTRY_USER: ${{secrets.CONTAINER_REGISTRY_USER}}
        CONTAINER_REGISTRY_TOKEN: ${{secrets.CONTAINER_REGISTRY_TOKEN}}
      run: |
        cd gestion-exam-resultat
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python deploy-image.py --registry "$CONTAINER_REGISTRY" --registry-token "$CONTAINER_REGISTRY_TOKEN" \
        --registry-user "$CONTAINER_REGISTRY_USER"
