name: Gestion laboratoire CI/CD

on:
  push:
    branches:
      - branch-x
    paths:
      - "gestion-laboratoire/**"
  pull_request:
    branches:
      - branch-x
    paths:
      - "gestion-laboratoire/**"

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./gestion-laboratoire

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: |
          export VERSION="$(cat version.txt)"
          ./gradlew build -x test

      - name: Perform testing
        run: |
          export CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}
          ./gradlew test
